export const ERROR_CODES = {
  UNKNOWN: "UNKNOWN",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  CONFIG_MISSING: "CONFIG_MISSING",
  CONFIG_INVALID: "CONFIG_INVALID",
  INFRASTRUCTURE_FAILURE: "INFRASTRUCTURE_FAILURE",
  DATABASE_NOT_INITIALIZED: "DATABASE_NOT_INITIALIZED",
  DATABASE_CONNECTION_FAILED: "DATABASE_CONNECTION_FAILED",
  DOMAIN_RULE_VIOLATION: "DOMAIN_RULE_VIOLATION",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];